import { Contact } from '../types/contact';

export const INITIAL_CONTACT_RELATIONSHIPS = [
  'Family',
  'Friend',
  'Partner',
  'Coworker',
  'Manager',
  'Medical',
  'Professional',
  'Emergency Contact',
  'Other',
];

export const INITIAL_CONTACT_CATEGORIES = [
  'Personal',
  'Work',
  'Health',
  'Services',
  'VIP',
];

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'contact-dr-miller',
    fullName: 'Dr. Sarah Miller',
    displayName: 'Dr. Miller',
    phoneNumber: '+61 400 123 456',
    email: 'reception@millerclinic.com.au',
    address: '124 Collins St, Melbourne VIC 3000',
    relationship: 'Medical',
    category: 'Health',
    notes: 'Family GP & Dental surgery contact.',
    birthday: '1982-05-14',
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'contact-sam-wilson',
    fullName: 'Samuel Wilson',
    displayName: 'Sam',
    phoneNumber: '+61 411 987 654',
    secondaryPhoneNumber: '+61 3 9876 5432',
    email: 'sam.wilson@gmail.com',
    address: '42 River Rd, Richmond VIC 3121',
    relationship: 'Friend',
    category: 'Personal',
    notes: 'Weekend cycling & dinner mate.',
    birthday: '1995-11-23',
    createdAt: new Date(Date.now() - 86400000 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: 'contact-alex-reed',
    fullName: 'Alex Reed',
    displayName: 'Alex (Shift Manager)',
    phoneNumber: '+61 422 555 789',
    email: 'alex.reed@workplace.com.au',
    address: '88 Bourke St, Melbourne VIC 3000',
    relationship: 'Manager',
    category: 'Work',
    notes: 'Hospitality roster & shift coordination.',
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'contact-emma-taylor',
    fullName: 'Emma Taylor',
    displayName: 'Emma',
    phoneNumber: '+61 433 888 111',
    email: 'emma.taylor@emergency.org',
    relationship: 'Emergency Contact',
    category: 'Personal',
    notes: 'Primary next of kin & emergency contact.',
    birthday: '1996-08-30',
    createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];
